/**
 * @prufs/git-bridge - exporter.ts
 *
 * PrufsGitExporter: one-way snapshot export from @prufs/store to a Git remote.
 *
 * One Git commit per export run. Not one per CausalCommit.
 *
 * What is exported (the file tree at HEAD):
 *   - File paths and their content blobs as resolved by the Prufs store
 *   - A synthetic commit message carrying the Prufs HEAD commit_id for
 *     audit correlation
 *
 * What is NOT exported (deliberately stripped):
 *   - TrailSnapshot (causal graph, decision nodes, edges)
 *   - AgentAttestation (agent_id, model_id, session_id, signatures)
 *   - graph_hash, tree_hash, commit_signature
 *   - Any Prufs-internal metadata
 *
 * The Git mirror is read-only from Git's perspective.
 * Prufs never reads from it. It exists solely to keep Git-dependent
 * CI/CD pipelines alive during team transition.
 */

import * as git from 'isomorphic-git';
import * as http from 'isomorphic-git/http/node';
import * as fs from 'node:fs';
import * as fsp from 'node:fs/promises';
import * as path from 'node:path';
import * as os from 'node:os';
import type { BridgeConfig, BranchExportConfig, GitAuthConfig } from './config.js';

// ---------------------------------------------------------------------------
// Store interface (duck-typed to avoid runtime dep on @prufs/store)
// ---------------------------------------------------------------------------

interface ContentBlob {
  path: string;
  content_hash: string;
  content?: string;
  change_type: 'added' | 'modified' | 'deleted';
}

interface CausalCommit {
  commit_id: string;
  parent_hash: string;
  timestamp: string;
  message: string;
  branch?: string;
  changeset: { changed: ContentBlob[]; tree_hash: string };
}

export interface PrufsStoreAdapter {
  head(branch?: string): CausalCommit | undefined;
  log(branch?: string, limit?: number): CausalCommit[];
  resolve(path: string, branch?: string): string | undefined;
  blobs(commitId: string): ContentBlob[];
}

// ---------------------------------------------------------------------------
// Export result
// ---------------------------------------------------------------------------

export interface ExportResult {
  /** ISO timestamp of when this export ran */
  run_at: string;
  /** Prufs branch that was exported */
  prufs_branch: string;
  /** Git branch that received the snapshot */
  git_branch: string;
  /** Prufs HEAD commit_id at time of export (for audit correlation) */
  prufs_head_commit_id: string;
  /** Whether the export pushed anything (false if no changes since last run) */
  pushed: boolean;
  /** Number of files in the exported tree */
  file_count: number;
  /** Any error message if the export failed */
  error?: string;
  /** Whether this run succeeded */
  ok: boolean;
}

// ---------------------------------------------------------------------------
// Synthetic commit message
// ---------------------------------------------------------------------------

function buildCommitMessage(
  prufs_branch: string,
  head_commit_id: string,
  timestamp: string
): string {
  return [
    `prufs-snapshot: ${prufs_branch}`,
    ``,
    `prufs-head: ${head_commit_id}`,
    `prufs-branch: ${prufs_branch}`,
    `export-time: ${timestamp}`,
    ``,
    `---`,
    `This commit was generated by @prufs/git-bridge.`,
    `It is a lossy read-only snapshot of the Prufs file tree at HEAD.`,
    `The full decision trail lives in the Prufs store and is not present here.`,
    `To inspect the causal reasoning behind this snapshot, query:`,
    `  prufs log --commit ${head_commit_id}`,
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Auth callback for isomorphic-git
// ---------------------------------------------------------------------------

function buildAuthCallback(auth: GitAuthConfig) {
  return () => {
    if (auth.type === 'token') {
      return { username: 'token', password: auth.token };
    }
    // SSH handled by git itself via keyPath config; return empty for HTTPS
    return {};
  };
}

// ---------------------------------------------------------------------------
// File tree reconstruction
// ---------------------------------------------------------------------------

/**
 * Walk the Prufs store log for a branch and collect the full file tree
 * at HEAD - one entry per path, using the most recent content for each path.
 *
 * This is O(commits * files) in the worst case but the store's resolve()
 * handles the heavy lifting. We collect all paths first, then resolve each.
 */
async function reconstructTree(
  store: PrufsStoreAdapter,
  prufs_branch: string
): Promise<Map<string, string>> {
  const head = store.head(prufs_branch);
  if (!head) return new Map();

  // Collect every path that has ever appeared on this branch
  const allCommits = store.log(prufs_branch, 10000);
  const allPaths = new Set<string>();
  for (const commit of allCommits) {
    for (const blob of commit.changeset.changed) {
      allPaths.add(blob.path);
    }
  }

  // For each path, resolve to latest non-deleted content
  const tree = new Map<string, string>();
  for (const filePath of allPaths) {
    // Check if the most recent change was a deletion
    const latestCommitWithPath = allCommits.find((c) =>
      c.changeset.changed.some((b) => b.path === filePath)
    );
    if (!latestCommitWithPath) continue;
    const latestBlob = latestCommitWithPath.changeset.changed.find(
      (b) => b.path === filePath
    );
    if (latestBlob?.change_type === 'deleted') continue;

    const content = store.resolve(filePath, prufs_branch);
    if (content !== undefined) {
      tree.set(filePath, content);
    }
  }

  return tree;
}

// ---------------------------------------------------------------------------
// PrufsGitExporter
// ---------------------------------------------------------------------------

export class PrufsGitExporter {
  private config: BridgeConfig;
  private store: PrufsStoreAdapter;
  private exportHistory: ExportResult[] = [];
  private lastExportedHead: Map<string, string> = new Map();

  constructor(store: PrufsStoreAdapter, config: BridgeConfig) {
    this.store = store;
    this.config = config;
  }

  // -------------------------------------------------------------------------
  // exportBranch() - run one snapshot export for a single branch
  // -------------------------------------------------------------------------

  async exportBranch(branchConfig: BranchExportConfig): Promise<ExportResult> {
    const run_at = new Date().toISOString();
    const prufs_branch = branchConfig.prufs_branch;
    const git_branch = branchConfig.git_branch ?? prufs_branch;

    const result: ExportResult = {
      run_at,
      prufs_branch,
      git_branch,
      prufs_head_commit_id: '',
      pushed: false,
      file_count: 0,
      ok: false,
    };

    let workDir: string | undefined;

    try {
      // 1. Find HEAD
      const head = this.store.head(prufs_branch);
      if (!head) {
        result.error = `No HEAD found for branch '${prufs_branch}' - nothing to export`;
        result.ok = true; // not an error, just an empty branch
        return result;
      }

      result.prufs_head_commit_id = head.commit_id;

      // 2. Skip if HEAD has not changed since last export
      const lastHead = this.lastExportedHead.get(prufs_branch);
      if (lastHead === head.commit_id) {
        result.pushed = false;
        result.ok = true;
        result.file_count = 0;
        if (this.config.verbose !== false) {
          console.log(
            `[prufs-git-bridge] ${prufs_branch}: no changes since last export (HEAD=${head.commit_id.slice(0, 12)}), skipping`
          );
        }
        return result;
      }

      // 3. Reconstruct file tree
      const tree = await reconstructTree(this.store, prufs_branch);
      result.file_count = tree.size;

      // 4. Set up working directory
      workDir = await this.ensureMirrorDir(git_branch);

      // 5. Write files into working directory
      await this.writeTree(workDir, tree);

      // 6. Git operations: stage, commit, push
      await this.gitStageAll(workDir);

      const hasChanges = await this.hasUncommittedChanges(workDir);
      if (!hasChanges) {
        result.pushed = false;
        result.ok = true;
        this.lastExportedHead.set(prufs_branch, head.commit_id);
        return result;
      }

      const commitMessage = buildCommitMessage(prufs_branch, head.commit_id, run_at);
      await this.gitCommit(workDir, commitMessage, git_branch);
      await this.gitPush(workDir, git_branch);

      // 7. Record success
      this.lastExportedHead.set(prufs_branch, head.commit_id);
      result.pushed = true;
      result.ok = true;

      if (this.config.verbose !== false) {
        console.log(
          `[prufs-git-bridge] ${prufs_branch} -> ${git_branch}: exported ${tree.size} files, HEAD=${head.commit_id.slice(0, 12)}`
        );
      }
    } catch (err) {
      result.error = err instanceof Error ? err.message : String(err);
      result.ok = false;
      console.error(`[prufs-git-bridge] Export failed for ${prufs_branch}:`, result.error);
    }

    return result;
  }

  // -------------------------------------------------------------------------
  // exportAll() - run one snapshot export for all configured branches
  // -------------------------------------------------------------------------

  async exportAll(): Promise<ExportResult[]> {
    const results: ExportResult[] = [];
    for (const branchConfig of this.config.branches) {
      const result = await this.exportBranch(branchConfig);
      results.push(result);
      this.recordHistory(result);
    }
    return results;
  }

  // -------------------------------------------------------------------------
  // history() - return the last N export results
  // -------------------------------------------------------------------------

  history(limit?: number): ExportResult[] {
    const n = limit ?? this.exportHistory.length;
    return this.exportHistory.slice(-n);
  }

  // -------------------------------------------------------------------------
  // Private Git operations (isomorphic-git)
  // -------------------------------------------------------------------------

  private async ensureMirrorDir(git_branch: string): Promise<string> {
    const dir = path.join(this.config.mirror_dir, git_branch.replace(/\//g, '__'));
    await fsp.mkdir(dir, { recursive: true });

    // Init repo if not already initialised
    const gitDir = path.join(dir, '.git');
    const isRepo = fs.existsSync(gitDir);
    if (!isRepo) {
      await git.init({ fs, dir });
      await git.setConfig({ fs, dir, path: 'user.name', value: this.config.author.name });
      await git.setConfig({ fs, dir, path: 'user.email', value: this.config.author.email });
    }

    return dir;
  }

  private async writeTree(dir: string, tree: Map<string, string>): Promise<void> {
    // Remove all tracked files first (clean slate, mirrors deletions)
    const existing = await fsp.readdir(dir);
    for (const entry of existing) {
      if (entry === '.git') continue;
      await fsp.rm(path.join(dir, entry), { recursive: true, force: true });
    }

    // Write current tree
    for (const [filePath, content] of tree) {
      const fullPath = path.join(dir, filePath);
      await fsp.mkdir(path.dirname(fullPath), { recursive: true });
      await fsp.writeFile(fullPath, content, 'utf8');
    }
  }

  private async gitStageAll(dir: string): Promise<void> {
    await git.add({ fs, dir, filepath: '.' });
  }

  private async hasUncommittedChanges(dir: string): Promise<boolean> {
    try {
      const matrix = await git.statusMatrix({ fs, dir });
      // statusMatrix returns [filepath, HEAD, workdir, stage]
      // Any row where workdir or stage != 1 (unmodified) means changes
      return matrix.some(([, head, workdir, stage]) => {
        return head !== 1 || workdir !== 1 || stage !== 1;
      });
    } catch {
      // If HEAD doesn't exist yet (first commit), there are always changes
      return true;
    }
  }

  private async gitCommit(dir: string, message: string, branch: string): Promise<void> {
    // Ensure we are on the right branch
    try {
      await git.resolveRef({ fs, dir, ref: 'HEAD' });
    } catch {
      // No commits yet - first commit
    }

    await git.commit({
      fs,
      dir,
      message,
      author: {
        name: this.config.author.name,
        email: this.config.author.email,
      },
      ref: branch,
    });
  }

  private async gitPush(dir: string, branch: string): Promise<void> {
    await git.push({
      fs,
      http,
      dir,
      remote: 'origin',
      remoteRef: branch,
      url: this.config.remote_url,
      onAuth: buildAuthCallback(this.config.auth),
      force: true, // snapshot exports always force-push; the mirror is not a collaboration surface
    });
  }

  // -------------------------------------------------------------------------
  // History management
  // -------------------------------------------------------------------------

  private recordHistory(result: ExportResult): void {
    this.exportHistory.push(result);
    const limit = this.config.history_limit ?? 100;
    if (this.exportHistory.length > limit) {
      this.exportHistory = this.exportHistory.slice(-limit);
    }
  }
}
